-- Create database if not exists, PSQL style
SELECT 'CREATE DATABASE {FILL_HERE}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{FILL_HERE}')\gexec
CREATE USER {FILL_HERE} WITH PASSWORD '{FILL_HERE}';
GRANT ALL PRIVILEGES ON DATABASE {FILL_HERE} TO {FILL_HERE};
ALTER DATABASE {FILL_HERE} OWNER TO {FILL_HERE};
GRANT ALL ON SCHEMA public TO {FILL_HERE};