version: '3'

services:
  web:
    restart: always
    working_dir: /app/Project
    network_mode: host
    image: ${DOCKER_REGISTRY_URL}:${TAG}
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      celery:
        condition: service_started
      init-web:
        condition: service_completed_successfully
    command: python3 -m gunicorn config.asgi:application --bind 0.0.0.0 -k uvicorn.workers.UvicornWorker

  celery:
    restart: always
    working_dir: /app/Project
    network_mode: host
    image: ${DOCKER_REGISTRY_URL}:${TAG}
    command: celery -A Project worker -l debug
    env_file:
      - .env

  # Run migration on init.
  init-web:
    working_dir: /app/Project
    network_mode: host
    image: ${DOCKER_REGISTRY_URL}:${TAG}
    command: bash -c './manage.py collectstatic --noinput; ./manage.py migrate;'
    env_file:
      - .env
